### ISSUE TITLE
"Something went wrong downloading JavaScript files"

### ISSUE THREAD

**Issue by Jme7** [GuilhermeRossato/3D-Redstone-Simulator#17]
I went to http://grossato.com/3D-Redstone-Simulator/ (This project in webpage form), and after a bit of waiting it presented me with the message "Something went wrong downloading JavaScript files". I have Windows 10 x64 bit. Ask for any other information you need.

**Comment by GuilhermeRossato** [comment]
Thanks, checked and there is indeed something wrong there: one of the resources responds with 404 error and causes this problem. Will be fixing asap!

**Comment by GuilhermeRossato** [comment]
Fixed with [b9ebcdb](https://github.com/GuilhermeRossato/3D-Redstone-Simulator/commit/b9ebcdb2e816d1fbdb0069113783ce23e4691ace).

**Comment by Jme7** [comment]
Thanks!

**Comment by Jme7** [comment]
If I may ask, how do you use it? I can't seem to get into edit mode.

**Comment by GuilhermeRossato** [comment]
Sadly that is not yet implemented, worlds are currently constructed by the `mockWorld` method in the `scripts/App.js` class.

**Comment by Jme7** [comment]
Ok, just wondering, thanks for the help!
